### ISSUE TITLE
PBP display inaccurate in Human vs. PC play

### ISSUE THREAD

**Issue by bsimbro** [jleonard2099/LHG_Baseball#10]
1st thanks for revival and best of luck with future. Full Count seems to run fine in non stadium mode,but if I use the stadiums the play by play doesn't go into the play b)y play box the first line appears above the box and the play concludes behind the scenes.It only seems to happen for the visiting team,looks ok at bottom of inning. tried on two different machines 1)HP Victus 15L running windows 11 on an external monitor 2)older Surface 3 running Windows 10 on native screen.Also the menu descriptions seem to overwrite(livable but annoying as most of us familiar with the game have probably memorized the numbers

**Comment by jleonard2099** [comment]
Thanks! This confirms it for me, i just discovered similar PBP behavior earlier. i had not tested human play previously, it uses the same routines so i'll be curious what i missed but i plan on trying to address it this week. The menu descriptions I haven't seen yet;  screenshots are appreciated if possible.

**Comment by bsimbro** [comment]
Might not be possible before Thursday,but I'll try for earlier

    On Monday, January 2, 2023, 02:18:13 PM EST, Jason Leonard ***@***.***> wrote:  
 
 


Thanks! This confirms it for me, i just discovered similar PBP behavior earlier. i had not tested human play previously, it uses the same routines so i'll be curious what i missed but i plan on trying to address it this week. The menu descriptions I haven't seen yet; screenshots are appreciated if possible.

**Comment by jleonard2099** [comment]
While waiting for further screenshots from the "menu" oddities, it should be clarified here what is occuring:

- When PBP text is first display in PC vs Human, it shows 1 line above the "black" PBP box
- This text is also showing in "black" text
- It is suspected that the remaining PBP is printing, but nobody notices because it's "black" on "black"
- The fix will likely involve correcting the positioning and text color of PBP when not autplayed.

**Comment by jleonard2099** [comment]
The screen print did not come through. Did you save it as a file first? I
would recommend that; then you can attach it to the conversation.



[image: logo_in_nav_44x36.png]
<https://www.linkedin.com/pub/jason-leonard/9a/43/735>

Galatians 6:9

Jason Leonard

email: ***@***.***

mobile: 302-559-8645

**Comment by bsimbro** [comment]
This attempt is from my Surface 3 the attachments are .png files and appear on this end when I preview the reply. More issues keep creeping in as I try different machines/seasons The Batter stats  appear to be 1/10 actual (small sample size,but earlier in the game Willie Mays was at .025 or so and Carl Yastrzemski was at .030 I was running 1968 (The year of the pitcher,but that seems to be a display issue 
    On Wednesday, January 4, 2023 at 08:53:34 AM EST, Jason Leonard ***@***.***> wrote:  
 
 

The screen print did not come through. Did you save it as a file first? I
would recommend that; then you can attach it to the conversation.



[image: logo_in_nav_44x36.png]
<https://www.linkedin.com/pub/jason-leonard/9a/43/735>

Galatians 6:9

Jason Leonard

email: ***@***.***

mobile: 302-559-8645

**Comment by jleonard2099** [comment]
Attaching 2 screenshots of what I was able to witness the first time around.
![2023-01-02 10_39_15-Full Count Baseball - PLAY BALL!](https://user-images.githubusercontent.com/100517658/212482067-a129a48f-3f61-44a7-b24a-3e732ebccf57.png)
![2023-01-02 10_40_07-Full Count Baseball - PLAY BALL!](https://user-images.githubusercontent.com/100517658/212482068-b878111a-5fb9-4fcb-afe9-a75f89d1e354.png)

**Comment by bsimbro** [comment]
Thanks,I got this top screen one line,but didn't get the bunched line like in screen 2,my bunched lines were on the menu screen as I forwarded,probably a similar cause

    On Tuesday, January 3, 2023 at 11:22:07 AM EST, Jason Leonard ***@***.***> wrote:  
 
 


While waiting for further screenshots from the "menu" oddities, it should be clarified here what is occuring:
   
   - When PBP text is first display in PC vs Human, it shows 1 line above the "black" PBP box
   - This text is also showing in "black" text
   - It is suspected that the remaining PBP is printing, but nobody notices because it's "black" on "black"
   - The fix will likely involve correcting the positioning and text color of PBP when not autplayed.

**Comment by jleonard2099** [comment]
At this point I have text showing up in the PBP box correctly (white text on black) and not on the image. This was tricky because the original code didn't have a PBP function, I created one based on Basketball. I was literally placing the text 1 row above where needed. The odd part is that during most of my testing, it printed in the right area.  But that was when no PBP delay was still printing text (it shouldn't). Somewhere along the line something must have been giving it a higher value.

The text overwriting itself will be an easy fix, it's just not clear why it happens. My code restores the image graphic everywhere the original does (essentially pasting the image in place before writing the text).  So clearly, this is getting missed along the way  and the text is just laying on top.

I anticipate having this corrected later today and then have several bugs to go through with the GUI and stats before a release.

**Comment by bsimbro** [comment]
Thanks for keeping me informed,look forward to trying the revision

Sent from the all new AOL app for Android 
 
  On Tue, Jan 17, 2023 at 1:23 PM, Jason ***@***.***> wrote:   


At this point I have text showing up in the PBP box correctly (white text on black) and not on the image. This was tricky because the original code didn't have a PBP function, I created one based on Basketball. I was literally placing the text 1 row above where needed. The odd part is that during most of my testing, it printed in the right area. But that was when no PBP delay was still printing text (it shouldn't). Somewhere along the line something must have been giving it a higher value.

The text overwriting itself will be an easy fix, it's just not clear why it happens. My code restores the image graphic everywhere the original does (essentially pasting the image in place before writing the text). So clearly, this is getting missed along the way and the text is just laying on top.

I anticipate having this corrected later today and then have several bugs to go through with the GUI and stats before a release.

**Comment by jleonard2099** [comment]
LOL okay this is completed fixed now. I had commented out the code for backing up where the text is written because I couldn't figure out where it was needed. It's only needed during human play however. Next release will have working human play.

**Comment by bsimbro** [comment]
Sorry for the delay,attached are screen shots indicating the phantom runner bottom of 2nd inning 1 out 1st is George Scott at bat,next shows Scott at First Base,Jenkins hit count is up by 1 but no play by play result indicated a hit,just advanced to next batter. It's been years since I played the original so don't know if there's an underlying issue or not .Again,thanks for some great revisions,I tried football and basketball briefly but am not familiar enough to critique.    On Tuesday, January 17, 2023 at 06:52:47 PM EST, Jason Leonard ***@***.***> wrote:  
 
 


LOL okay this is completed fixed now. I had commented out the code for backing up where the text is written because I couldn't figure out where it was needed. It's only needed during human play however. Next release will have working human play.

**Comment by bsimbro** [comment]
Happened again in same game but screen shots were corrupted,tried again today Lou Brock on 3rd,next batter gets phantom hit,screen briefly indicates Brock scored but no mention of hit and next screen has runner on 1st
Thanks again
    On Saturday, January 28, 2023 at 12:55:01 PM EST, Bruce Simbro ***@***.***> wrote:  
 
  
Sorry for the delay,attached are screen shots indicating the phantom runner bottom of 2nd inning 1 out 1st is George Scott at bat,next shows Scott at First Base,Jenkins hit count is up by 1 but no play by play result indicated a hit,just advanced to next batter. It's been years since I played the original so don't know if there's an underlying issue or not .Again,thanks for some great revisions,I tried football and basketball briefly but am not familiar enough to critique.    On Tuesday, January 17, 2023 at 06:52:47 PM EST, Jason Leonard ***@***.***> wrote:  
 
 


LOL okay this is completed fixed now. I had commented out the code for backing up where the text is written because I couldn't figure out where it was needed. It's only needed during human play however. Next release will have working human play.

**Comment by jleonard2099** [comment]
I appreciate it! I'll look into it when I get a chance.



[image: logo_in_nav_44x36.png]
<https://www.linkedin.com/pub/jason-leonard/9a/43/735>

Galatians 6:9

Jason Leonard

email: ***@***.***

mobile: 302-559-8645

**Comment by bsimbro** [comment]
Forgot to mention it,it's human versus computer,not human opponent

Sent from the all new AOL app for Android 
 
  On Sun, Jan 29, 2023 at 1:47 PM, Jason ***@***.***> wrote:   

I appreciate it! I'll look into it when I get a chance.



[image: logo_in_nav_44x36.png]
<https://www.linkedin.com/pub/jason-leonard/9a/43/735>

Galatians 6:9

Jason Leonard

email: ***@***.***

mobile: 302-559-8645

**Comment by jleonard2099** [comment]
Thanks. I will have an updated release late this week as I've been dialed
in on everything to do with stats keeping across all games. Got reports of
similar behavior from someone else too so I just need time to set the game
up to log the PBP.



[image: logo_in_nav_44x36.png]
<https://www.linkedin.com/pub/jason-leonard/9a/43/735>

Galatians 6:9

Jason Leonard

email: ***@***.***

mobile: 302-559-8645

**Comment by bsimbro** [comment]
Trying revision,I'll try to get screen prints later this week. I realize the in game.EXE changes are still coming,but I just got the pitching change that wasn't that others have mentioned,the phantom runners still occur,and the in game batting averages are still too low. Appreciate the effort and it must be a challenge to work with nearly 30 year code.
    On Tuesday, January 17, 2023 at 06:52:47 PM EST, Jason Leonard ***@***.***> wrote:  
 
 


LOL okay this is completed fixed now. I had commented out the code for backing up where the text is written because I couldn't figure out where it was needed. It's only needed during human play however. Next release will have working human play.

**Comment by jleonard2099** [comment]
It is only because following the intention of code that doesn't have modern
logic structures...is tricky.

More importantly the baseball game is super complex.

I appreciate you giving me any information you can. When I have time to
play it will help. I may have to compare everything line by line though.
Again.
